apiVersion: v1
kind: Service
metadata:
  name: audit-service
  namespace: ecommerce-ciam
  labels:
    app: audit-service
    app.kubernetes.io/name: audit-service
    app.kubernetes.io/component: audit
    app.kubernetes.io/part-of: ecommerce-ciam
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: ClusterIP
  selector:
    app: audit-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
    - name: management
      protocol: TCP
      port: 8081
      targetPort: management
  sessionAffinity: None
