apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  namespace: ecommerce-ciam
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: ecommerce-ciam
    environment: prod
spec:
  # API Gateway must always have at least 3 pods for HA and performance
  minAvailable: 3
  selector:
    matchLabels:
      app: api-gateway
